[package]
name = "tauri_devtools"
authors.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri_devtools_wire_format = { path = "../wire" }
tracing.workspace = true
tracing-core.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }
tokio-stream = { workspace = true, features = ["sync"] }
futures.workspace = true
tauri.workspace = true

tonic = "0.10"
prost = "0.12"
tonic-web = "0.10"
tonic-health = "0.10"
tower-http = "0.4"
prost-types = "0.12"

[dev-dependencies]
tauri = { workspace = true, features = ["test"] }
tracing-mock = { git = "https://github.com/tokio-rs/tracing", branch = "v0.1.x", features = ["tracing-subscriber"] }