[package]
name = "tauri-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tauri-example"
path = "main.rs"

[dependencies]
tauri = { git = "ssh://git@github.com/crabnebula-dev/tauri.git", branch = "feat/core-tracing" }
tauri-plugin-devtools = { path = "../../plugins/tauri" }
tracing = "0.1"
tokio = "1"
reqwest = { version = "0.11", features = ["blocking"]}

[build-dependencies]
tauri-build = { git = "ssh://git@github.com/crabnebula-dev/tauri.git", branch = "feat/core-tracing" }
