[package]
name = "tauri-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tauri-example"
path = "main.rs"

[dependencies]
tauri = "1.4.1"
inspector-protocol = { path = "../../inspector-protocol" }

[build-dependencies]
tauri-build = "1.4.0"