[package]
name = "tauri-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tauri-example"
path = "main.rs"

[dependencies]
tauri = { git = "https://github.com/crabnebula-dev/tauri.git", branch = "feat/core-tracing-v1" }
tauri_devtools = { path = "../../devtools" }
tracing = "0.1"
tokio = "1"
reqwest = "0.11"

[build-dependencies]
tauri-build = { git = "https://github.com/crabnebula-dev/tauri.git", branch = "feat/core-tracing-v1" }