[package]
name = "tauri-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tauri-example"
path = "main.rs"

[dependencies]
tauri = "1.4.1"
tauri-plugin-devtools = { path = "../../plugins/tauri" }
tracing = "0.1"
tokio = "1"
reqwest = "0.11"

[build-dependencies]
tauri-build = "1.4.0"