use fst::Map;
use std::path::Path;
use std::{env, fs, mem};

fn main() {
    let out_dir = env::var_os("OUT_DIR").unwrap();

    let ext_icons_path = Path::new(&out_dir).join("ext_icons.bin");
    let ext_icons =
        Map::from_iter(EXT_ICONS.iter().map(|(ext, icon)| (ext, icon.as_u64()))).unwrap();
    fs::write(&ext_icons_path, ext_icons.into_fst().as_bytes()).unwrap();

    let filename_icons_path = Path::new(&out_dir).join("filename_icons.bin");
    let filename_icons =
        Map::from_iter(EXT_ICONS.iter().map(|(ext, icon)| (ext, icon.as_u64()))).unwrap();
    fs::write(&filename_icons_path, filename_icons.into_fst().as_bytes()).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}

#[repr(u64)]
#[derive(Copy, Clone, Debug)]
pub enum Icon {
    Access,
    Actionscript,
    Ada,
    Advpl,
    Affectscript,
    Affinitydesigner,
    Affinityphoto,
    Affinitypublisher,
    Ai,
    Al,
    Allcontributors,
    Angular,
    Ansible,
    Antlr,
    Anyscript,
    Apache,
    ApiExtractor,
    Apib,
    Apl,
    Applescript,
    Appscript,
    Appsemble,
    Appveyor,
    Arduino,
    Asciidoc,
    Asp,
    Aspx,
    Assembly,
    Astro,
    Astroconfig,
    Ats,
    Audio,
    Aurelia,
    Autohotkey,
    Autoit,
    Avif,
    Avro,
    Awk,
    Azure,
    Azurepipelines,
    Babel,
    Ballerina,
    Bat,
    Bats,
    Bazaar,
    Bazel,
    BazelIgnore,
    BazelVersion,
    Befunge,
    Bicep,
    Biml,
    Binary,
    Biome,
    Bitbucketpipeline,
    Bithound,
    Blade,
    Blitzbasic,
    Bolt,
    Bosque,
    Bower,
    Browserslist,
    Buckbuild,
    Buf,
    Bun,
    Bundler,
    Bunfig,
    C,
    CAl,
    Cabal,
    Caddy,
    Cake,
    Capacitor,
    Cargo,
    Casc,
    Cddl,
    Cert,
    Ceylon,
    Cf,
    Cfc,
    Cfm,
    Cheader,
    Chef,
    ChefCookbook,
    Circleci,
    Class,
    Clojure,
    Clojurescript,
    Cmake,
    Cobol,
    Codacy,
    Codeclimate,
    Codecov,
    Codekit,
    Codeowners,
    Codeql,
    Coffeelint,
    Coffeescript,
    Commitizen,
    Commitlint,
    Composer,
    Conan,
    Conda,
    Config,
    Confluence,
    Coveralls,
    Cpp,
    Cppheader,
    Crowdin,
    Crystal,
    Csharp,
    Cspell,
    Csproj,
    Css,
    Csscomb,
    Csslint,
    Cssmap,
    Cucumber,
    Cuda,
    Cvs,
    Cypress,
    CypressSpec,
    Cython,
    Dal,
    Darcs,
    Dartlang,
    Db,
    Delphi,
    Deno,
    Denoify,
    Dependabot,
    Dependencies,
    Devcontainer,
    Dhall,
    Diff,
    Dlang,
    Docker,
    Dockertest,
    Docpad,
    Docz,
    Dojo,
    Doppler,
    Dotenv,
    Doxygen,
    Drawio,
    Drone,
    Drools,
    Dustjs,
    Dylan,
    Earthly,
    EasMetadata,
    Edge,
    Editorconfig,
    Eex,
    Ejs,
    Elastic,
    Eleventy,
    Elixir,
    Elm,
    Emacs,
    Ember,
    Ensime,
    Eps,
    Erb,
    Erlang,
    Esbuild,
    Eslint,
    Excel,
    Expo,
    Falcon,
    Fantasticon,
    Fauna,
    Favicon,
    Fbx,
    Firebase,
    Firebasehosting,
    Firestore,
    Fitbit,
    Fla,
    Flareact,
    Flash,
    Floobits,
    Flow,
    Flutter,
    FlutterPackage,
    Font,
    Formkit,
    Fortran,
    Fossa,
    Fossil,
    Freemarker,
    Fsharp,
    Fsproj,
    Fthtml,
    Funding,
    Fusebox,
    Galen,
    Gamemaker,
    Gatsby,
    Gcloud,
    Gcode,
    Gdscript,
    Genstat,
    Git,
    Gitlab,
    Gitpod,
    Glide,
    Glitter,
    Glsl,
    Glyphs,
    Gnu,
    Gnuplot,
    Go,
    GoPackage,
    GoWork,
    Goctl,
    Godot,
    Gradle,
    Grain,
    Graphql,
    GraphqlConfig,
    Graphviz,
    Greenkeeper,
    Gridsome,
    Groovy,
    Grunt,
    Gulp,
    Haml,
    Handlebars,
    Harbour,
    Hardhat,
    Hashicorp,
    Haskell,
    Haxe,
    Haxecheckstyle,
    Haxedevelop,
    Helix,
    Helm,
    Hjson,
    Hlsl,
    Horusec,
    Host,
    Html,
    Htmlhint,
    Http,
    Hunspell,
    Husky,
    Hy,
    Hygen,
    Hypr,
    Icl,
    Idris,
    Idrisbin,
    Idrispkg,
    Image,
    Imba,
    Inc,
    Infopath,
    Informix,
    Ini,
    Ink,
    Innosetup,
    Io,
    Iodine,
    Ionic,
    Jake,
    Janet,
    Jar,
    Jasmine,
    Java,
    Jbuilder,
    Jekyll,
    Jenkins,
    Jest,
    JestSnapshot,
    Jinja,
    Jpm,
    Js,
    Jsbeautify,
    Jsconfig,
    Jscpd,
    Jshint,
    Jsmap,
    Json,
    JsonSchema,
    Json5,
    Jsonld,
    Jsonnet,
    Jsp,
    Jss,
    Julia,
    Jupyter,
    K,
    Karma,
    Key,
    Kitchenci,
    Kite,
    Kivy,
    Kos,
    Kotlin,
    Kusto,
    Latino,
    Layout,
    Lerna,
    Less,
    Lex,
    License,
    Licensebat,
    Lighthouse,
    Lilypond,
    Lime,
    Lintstagedrc,
    Liquid,
    Lisp,
    Livescript,
    Lnk,
    Log,
    Lolcode,
    Lsl,
    Lua,
    Luau,
    Lync,
    Mailing,
    Manifest,
    ManifestBak,
    ManifestSkip,
    Map,
    Markdown,
    Markdownlint,
    MarkdownlintIgnore,
    Marko,
    Markojs,
    MasterCo,
    Matlab,
    Maven,
    Maxscript,
    Maya,
    Mdx,
    Mediawiki,
    Mercurial,
    Mermaid,
    Meson,
    Mjml,
    Mlang,
    Mocha,
    Modernizr,
    Mojo,
    Mojolicious,
    Moleculer,
    Mondoo,
    Mongo,
    Monotone,
    Motif,
    Mson,
    Mustache,
    Ndst,
    Nearly,
    Nestjs,
    Netlify,
    Next,
    NgTailwind,
    Nginx,
    Nim,
    Nimble,
    Ninja,
    Nix,
    Njsproj,
    Noc,
    Node,
    Nodemon,
    Npm,
    Nsi,
    Nsri,
    NsriIntegrity,
    Nuget,
    Numpy,
    Nunjucks,
    Nuxt,
    Nx,
    Nyc,
    Objectivec,
    Objectivecpp,
    Objidconfig,
    Ocaml,
    OcamlIntf,
    Ogone,
    Onenote,
    Opencl,
    OpenHab,
    Openscad,
    Org,
    Outlook,
    Ovpn,
    Package,
    Paket,
    Patch,
    Pcl,
    Pddl,
    PddlHappenings,
    PddlPlan,
    Pdf,
    Peeky,
    Perl,
    Perl6,
    Pgsql,
    Photoshop,
    Php,
    Phpcsfixer,
    Phpstan,
    Phpunit,
    Phraseapp,
    Pine,
    Pip,
    Pipeline,
    Plantuml,
    Platformio,
    Playwright,
    Plsql,
    PlsqlPackage,
    PlsqlPackageBody,
    PlsqlPackageHeader,
    PlsqlPackageSpec,
    Pm2,
    Pnpm,
    Poedit,
    Poetry,
    Polymer,
    Pony,
    Postcss,
    Postcssconfig,
    Postman,
    Powerpoint,
    Powershell,
    PowershellFormat,
    PowershellPsd,
    PowershellPsm,
    PowershellTypes,
    Preact,
    Precommit,
    Prettier,
    Prisma,
    Procfile,
    Progress,
    Prolog,
    Prometheus,
    Protobuf,
    Protractor,
    Publiccode,
    Publisher,
    Pug,
    Pulumi,
    Puppet,
    Purescript,
    Pyret,
    Python,
    Pythowo,
    Pytyped,
    Pyup,
    Q,
    Qbs,
    Qlikview,
    Qml,
    Qmldir,
    Qsharp,
    Quasar,
    R,
    Racket,
    Rake,
    Raml,
    Razor,
    Razzle,
    Reactjs,
    Reacttemplate,
    Reactts,
    Reason,
    Red,
    Registry,
    Rego,
    Rehype,
    Remark,
    Renovate,
    Replit,
    Rescript,
    Rest,
    Retext,
    Rexx,
    Riot,
    Rmd,
    Robotframework,
    Robots,
    Rollup,
    Rome,
    Ron,
    Rproj,
    Rspec,
    Rubocop,
    Ruby,
    Rust,
    RustToolchain,
    Sails,
    Saltstack,
    San,
    SapphireFrameworkCli,
    Sas,
    Sass,
    Sbt,
    Scala,
    Scilab,
    Script,
    Scss,
    Sdlang,
    Sentry,
    Sequelize,
    Serverless,
    Shaderlab,
    Shell,
    Shellcheck,
    Shuttle,
    Silverstripe,
    Sino,
    Siyuan,
    Sketch,
    Skipper,
    Slang,
    Slashup,
    Slice,
    Slim,
    Sln,
    Smarty,
    Snapcraft,
    Snaplet,
    Snort,
    Snyk,
    Solidarity,
    Solidity,
    Spacengine,
    Sparql,
    Spin,
    Sqf,
    Sql,
    Sqlite,
    Squirrel,
    Sss,
    Stan,
    Stata,
    Stencil,
    Storyboard,
    Storybook,
    Stryker,
    Stylable,
    Styled,
    Stylelint,
    StylishHaskell,
    Stylus,
    Sublime,
    Subversion,
    Svelte,
    Svelteconfig,
    Svg,
    Swagger,
    Swc,
    Swift,
    Swig,
    Symfony,
    Systemd,
    Systemverilog,
    T4Tt,
    Tamagui,
    Tauri,
    Tcl,
    Teal,
    Tera,
    Terraform,
    Test,
    Testcafe,
    Testjs,
    Testts,
    Tex,
    Text,
    Textile,
    Tfs,
    Tiltfile,
    Todo,
    Toit,
    Toml,
    Tox,
    Travis,
    Tree,
    Tres,
    Truffle,
    Trunk,
    Tsbuildinfo,
    Tscn,
    Tsconfig,
    Tslint,
    Tt,
    Ttcn,
    Tuc,
    Turbo,
    Twig,
    Typedoc,
    Typescript,
    Typescriptdef,
    Typo3,
    Uiua,
    Unibeautify,
    Unison,
    Unlicense,
    Unocss,
    Vagrant,
    Vala,
    VanillaExtract,
    Vapi,
    Vapor,
    Vash,
    Vb,
    Vba,
    Vbhtml,
    Vbproj,
    Vcxproj,
    Velocity,
    Vercel,
    Verilog,
    Vhdl,
    Video,
    Vim,
    Vite,
    Vitest,
    Volt,
    Vscode,
    VscodeTest,
    Vsix,
    Vsixmanifest,
    Vue,
    Vueconfig,
    Wallaby,
    Wally,
    Wasm,
    Watchmanconfig,
    Wdio,
    Webpack,
    Wenyan,
    Wercker,
    Wgsl,
    Wikitext,
    Windi,
    Wit,
    Wolfram,
    Word,
    Wpml,
    Wxml,
    Wxss,
    Xcode,
    Xfl,
    Xib,
    Xliff,
    Xmake,
    Xml,
    Xquery,
    Xsl,
    Yacc,
    Yaml,
    Yamllint,
    Yandex,
    Yang,
    Yarn,
    Yeoman,
    Zig,
    Zip,
}

impl Icon {
    pub fn as_u64(&self) -> u64 {
        unsafe { mem::transmute::<Self, u64>(*self) }
    }
}

pub const EXT_ICONS: [(&str, Icon); 679] = [
    ("3g2", Icon::Video),
    ("3gp", Icon::Video),
    ("4gl", Icon::Informix),
    ("7z", Icon::Zip),
    ("CMakeCache.txt", Icon::Cmake),
    ("Caddyfile", Icon::Caddy),
    ("Tiltfile", Icon::Tiltfile),
    ("a", Icon::Binary),
    ("aac", Icon::Audio),
    ("accda", Icon::Access),
    ("accdb", Icon::Access),
    ("accdc", Icon::Access),
    ("accde", Icon::Access),
    ("accdp", Icon::Access),
    ("accdr", Icon::Access),
    ("accdt", Icon::Access),
    ("accdu", Icon::Access),
    ("act", Icon::Audio),
    ("ada", Icon::Ada),
    ("ade", Icon::Access),
    ("adoc", Icon::Asciidoc),
    ("adp", Icon::Access),
    ("afdesign", Icon::Affinitydesigner),
    ("aff", Icon::Hunspell),
    ("affect", Icon::Affectscript),
    ("affinitydesigner", Icon::Affinitydesigner),
    ("affinityphoto", Icon::Affinityphoto),
    ("affinitypublisher", Icon::Affinitypublisher),
    ("afphoto", Icon::Affinityphoto),
    ("afpub", Icon::Affinitypublisher),
    ("ahk", Icon::Autohotkey),
    ("ai", Icon::Ai),
    ("aiff", Icon::Audio),
    ("al", Icon::Al),
    ("amr", Icon::Audio),
    ("amv", Icon::Video),
    ("ansible", Icon::Ansible),
    ("any", Icon::Anyscript),
    ("ape", Icon::Audio),
    ("api", Icon::Goctl),
    ("apib", Icon::Apib),
    ("apl", Icon::Apl),
    ("app", Icon::Binary),
    ("applescript", Icon::Applescript),
    ("arr", Icon::Pyret),
    ("as", Icon::Actionscript),
    ("ascx", Icon::Aspx),
    ("asf", Icon::Video),
    ("asm", Icon::Assembly),
    ("asp", Icon::Asp),
    ("aspx", Icon::Aspx),
    ("astro", Icon::Astro),
    ("ats", Icon::Ats),
    ("au", Icon::Audio),
    ("au3", Icon::Autoit),
    ("avcs", Icon::Avro),
    ("avi", Icon::Video),
    ("avif", Icon::Avif),
    ("awk", Icon::Awk),
    ("azcli", Icon::Azure),
    ("azure-pipelines.yml", Icon::Azurepipelines),
    ("bal", Icon::Ballerina),
    ("bat", Icon::Bat),
    ("bats", Icon::Bats),
    ("bazel", Icon::Bazel),
    ("bcmx", Icon::Outlook),
    ("bf", Icon::Befunge),
    ("bib", Icon::Tex),
    ("bicep", Icon::Bicep),
    ("biml", Icon::Biml),
    ("bin", Icon::Binary),
    ("bison", Icon::Yacc),
    ("blade.php", Icon::Blade),
    ("blitzbasic", Icon::Blitzbasic),
    ("bmp", Icon::Image),
    ("bolt", Icon::Bolt),
    ("br", Icon::Zip),
    ("bsq", Icon::Bosque),
    ("buf.yaml", Icon::Buf),
    ("bun", Icon::Bun),
    ("bz", Icon::Zip),
    ("bz2", Icon::Zip),
    ("bzip2", Icon::Zip),
    ("bzl", Icon::Bazel),
    ("c", Icon::C),
    ("cabal", Icon::Cabal),
    ("cake", Icon::Cake),
    ("cal", Icon::CAl),
    ("casc", Icon::Casc),
    ("cbl", Icon::Cobol),
    ("cddl", Icon::Cddl),
    ("cer", Icon::Cert),
    ("ceylon", Icon::Ceylon),
    ("cfc", Icon::Cfc),
    ("cfm", Icon::Cfm),
    ("cfml", Icon::Cf),
    ("cjs.map", Icon::Jsmap),
    ("ckbk", Icon::ChefCookbook),
    ("cl", Icon::Opencl),
    ("class", Icon::Class),
    ("clojure", Icon::Clojure),
    ("clojurescript", Icon::Clojurescript),
    ("cls", Icon::Vba),
    ("cma", Icon::Binary),
    ("cmake", Icon::Cmake),
    ("cmi", Icon::Binary),
    ("cmo", Icon::Binary),
    ("cmx", Icon::Binary),
    ("cmxa", Icon::Binary),
    ("code-snippets", Icon::Vscode),
    ("code-workspace", Icon::Vscode),
    ("coffee", Icon::Coffeescript),
    ("confluence", Icon::Confluence),
    ("cpp", Icon::Cpp),
    ("cr", Icon::Crystal),
    ("crec", Icon::Lync),
    ("crl", Icon::Cert),
    ("crt", Icon::Cert),
    ("cs", Icon::Csharp),
    ("cshtml", Icon::Razor),
    ("csproj", Icon::Csproj),
    ("csr", Icon::Cert),
    ("css", Icon::Css),
    ("css.map", Icon::Cssmap),
    ("css.ts", Icon::VanillaExtract),
    ("cu", Icon::Cuda),
    ("cy.cjs", Icon::CypressSpec),
    ("cy.coffee", Icon::CypressSpec),
    ("cy.js", Icon::CypressSpec),
    ("cy.jsx", Icon::CypressSpec),
    ("cy.mjs", Icon::CypressSpec),
    ("cy.ts", Icon::CypressSpec),
    ("cy.tsx", Icon::CypressSpec),
    ("d", Icon::Dlang),
    ("d.cts", Icon::Typescriptdef),
    ("d.mts", Icon::Typescriptdef),
    ("d.ts", Icon::Typescriptdef),
    ("dal", Icon::Dal),
    ("dart", Icon::Dartlang),
    ("db", Icon::Db),
    ("db3", Icon::Sqlite),
    ("dbgasm", Icon::Platformio),
    ("dct", Icon::Audio),
    ("ddl", Icon::Plsql),
    ("der", Icon::Cert),
    ("dhall", Icon::Dhall),
    ("diff", Icon::Diff),
    ("dio", Icon::Drawio),
    ("divx", Icon::Video),
    ("dll", Icon::Binary),
    ("do", Icon::Stata),
    ("doc", Icon::Word),
    ("dockerfile", Icon::Docker),
    ("docm", Icon::Word),
    ("docx", Icon::Word),
    ("dot", Icon::Word),
    ("dotm", Icon::Word),
    ("dotx", Icon::Word),
    ("dox", Icon::Doxygen),
    ("drawio", Icon::Drawio),
    ("drl", Icon::Drools),
    ("dss", Icon::Audio),
    ("dtx", Icon::Tex),
    ("dust", Icon::Dustjs),
    ("dvf", Icon::Audio),
    ("dylan", Icon::Dylan),
    ("earthfile", Icon::Earthly),
    ("eco", Icon::Docpad),
    ("edge", Icon::Edge),
    ("eex", Icon::Eex),
    ("ejs", Icon::Ejs),
    ("ejs.t", Icon::Hygen),
    ("el", Icon::Emacs),
    ("elc", Icon::Emacs),
    ("eleventy.js", Icon::Eleventy),
    ("elm", Icon::Elm),
    ("enc", Icon::License),
    ("ensime", Icon::Ensime),
    ("env", Icon::Dotenv),
    ("eot", Icon::Font),
    ("ep", Icon::Mojolicious),
    ("eps", Icon::Eps),
    ("erb", Icon::Erb),
    ("erl", Icon::Erlang),
    ("es", Icon::Elastic),
    ("eskip", Icon::Skipper),
    ("ex", Icon::Elixir),
    ("exe", Icon::Binary),
    ("exp", Icon::Tcl),
    ("f", Icon::Fortran),
    ("f4a", Icon::Video),
    ("f4b", Icon::Video),
    ("f4p", Icon::Video),
    ("f4v", Icon::Video),
    ("falcon", Icon::Falcon),
    ("fba", Icon::Fitbit),
    ("fbx", Icon::Fbx),
    ("feature", Icon::Cucumber),
    ("fla", Icon::Fla),
    ("flac", Icon::Audio),
    ("flex", Icon::Lex),
    ("flv", Icon::Video),
    ("fods", Icon::Excel),
    ("format.ps1xml", Icon::PowershellFormat),
    ("fql", Icon::Fauna),
    ("fs", Icon::Fsharp),
    ("fsproj", Icon::Fsproj),
    ("fthtml", Icon::Fthtml),
    ("ftl", Icon::Freemarker),
    ("g4", Icon::Antlr),
    ("gcode", Icon::Gcode),
    ("gd", Icon::Gdscript),
    ("gemfile", Icon::Bundler),
    ("gemfile.lock", Icon::Bundler),
    ("gen", Icon::Genstat),
    ("gif", Icon::Image),
    ("git", Icon::Git),
    ("glsl", Icon::Glsl),
    ("glyphs", Icon::Glyphs),
    ("gml", Icon::Gamemaker),
    ("go", Icon::Go),
    ("godot", Icon::Godot),
    ("gp", Icon::Gnuplot),
    ("gql", Icon::Graphql),
    ("gr", Icon::Grain),
    ("gradle", Icon::Gradle),
    ("groovy", Icon::Groovy),
    ("gs", Icon::Appscript),
    ("gsm", Icon::Audio),
    ("gspec", Icon::Galen),
    ("gv", Icon::Graphviz),
    ("gz", Icon::Zip),
    ("h", Icon::Cheader),
    ("h++", Icon::Cppheader),
    ("haml", Icon::Haml),
    ("happenings", Icon::PddlHappenings),
    ("haxe", Icon::Haxe),
    ("hbs", Icon::Handlebars),
    ("hcl", Icon::Hashicorp),
    ("helm.tpl", Icon::Helm),
    ("hh", Icon::Cppheader),
    ("hjson", Icon::Hjson),
    ("hl", Icon::Binary),
    ("hlsl", Icon::Hlsl),
    ("hosts", Icon::Host),
    ("hpp", Icon::Cppheader),
    ("hs", Icon::Haskell),
    ("htaccess", Icon::Apache),
    ("html", Icon::Html),
    ("html.stencil", Icon::Stencil),
    ("http", Icon::Http),
    ("hxp", Icon::Lime),
    ("hxproj", Icon::Haxedevelop),
    ("hxx", Icon::Cppheader),
    ("hy", Icon::Hy),
    ("hypr", Icon::Hypr),
    ("ibc", Icon::Idrisbin),
    ("ice", Icon::Slice),
    ("icl", Icon::Icl),
    ("icns", Icon::Image),
    ("ico", Icon::Image),
    ("id", Icon::Iodine),
    ("idr", Icon::Idris),
    ("iklax", Icon::Audio),
    ("ilk", Icon::Binary),
    ("imba", Icon::Imba),
    ("inc", Icon::Inc),
    ("include", Icon::Inc),
    ("infopathxml", Icon::Infopath),
    ("ini", Icon::Ini),
    ("ink", Icon::Ink),
    ("ino", Icon::Arduino),
    ("io", Icon::Io),
    ("ipkg", Icon::Idrispkg),
    ("ipynb", Icon::Jupyter),
    ("iss", Icon::Innosetup),
    ("iuml", Icon::Plantuml),
    ("ivs", Icon::Audio),
    ("janet", Icon::Janet),
    ("jar", Icon::Jar),
    ("java", Icon::Java),
    ("jbuilder", Icon::Jbuilder),
    ("jekyll", Icon::Jekyll),
    ("jenkins", Icon::Jenkins),
    ("jinja", Icon::Jinja),
    ("jl", Icon::Julia),
    ("jpeg", Icon::Image),
    ("jpg", Icon::Image),
    ("js", Icon::Js),
    ("js.flow", Icon::Flow),
    ("js.map", Icon::Jsmap),
    ("js.snap", Icon::JestSnapshot),
    ("json", Icon::Json),
    ("json-ld", Icon::Jsonld),
    ("json5", Icon::Json5),
    ("jsonc", Icon::Json),
    ("jsonld", Icon::Jsonld),
    ("jsonnet", Icon::Jsonnet),
    ("jsp", Icon::Jsp),
    ("jss", Icon::Jss),
    ("jsx", Icon::Reactjs),
    ("jsx.snap", Icon::JestSnapshot),
    ("k", Icon::K),
    ("key", Icon::Key),
    ("kit", Icon::Codekit),
    ("ks", Icon::Kos),
    ("kt", Icon::Kotlin),
    ("kusto", Icon::Kusto),
    ("kv", Icon::Kivy),
    ("laccdb", Icon::Access),
    ("lat", Icon::Latino),
    ("layout.htm", Icon::Layout),
    ("layout.html", Icon::Layout),
    ("ldb", Icon::Access),
    ("less", Icon::Less),
    ("lhs", Icon::Haskell),
    ("lib", Icon::Binary),
    ("lic", Icon::License),
    ("license", Icon::License),
    ("lidr", Icon::Idris),
    ("link", Icon::Systemd),
    ("liquid", Icon::Liquid),
    ("lisp", Icon::Lisp),
    ("lnk", Icon::Lnk),
    ("lockb", Icon::Bun),
    ("log", Icon::Log),
    ("lol", Icon::Lolcode),
    ("ls", Icon::Livescript),
    ("lsl", Icon::Lsl),
    ("lua", Icon::Lua),
    ("luau", Icon::Luau),
    ("ly", Icon::Lilypond),
    ("m", Icon::Objectivec),
    ("m2v", Icon::Video),
    ("m4a", Icon::Audio),
    ("m4b", Icon::Audio),
    ("m4p", Icon::Audio),
    ("m4v", Icon::Video),
    ("mam", Icon::Access),
    ("map", Icon::Map),
    ("maq", Icon::Access),
    ("marko", Icon::Marko),
    ("marko.js", Icon::Markojs),
    ("master", Icon::Layout),
    ("mat", Icon::Matlab),
    ("md", Icon::Markdown),
    ("mdb", Icon::Access),
    ("mdw", Icon::Access),
    ("mdx", Icon::Mdx),
    ("mediawiki", Icon::Mediawiki),
    ("mel", Icon::Maya),
    ("meson.build", Icon::Meson),
    ("mjml", Icon::Mjml),
    ("mjs.map", Icon::Jsmap),
    ("mk", Icon::Gnu),
    ("mk3d", Icon::Video),
    ("mkv", Icon::Video),
    ("ml", Icon::Ocaml),
    ("mli", Icon::OcamlIntf),
    ("mm", Icon::Objectivecpp),
    ("mmd", Icon::Mermaid),
    ("mmf", Icon::Audio),
    ("mo", Icon::Poedit),
    ("mogg", Icon::Audio),
    ("mojo", Icon::Mojo),
    ("mongo", Icon::Mongo),
    ("mov", Icon::Video),
    ("mp2", Icon::Video),
    ("mp3", Icon::Audio),
    ("mp4", Icon::Video),
    ("mpc", Icon::Audio),
    ("mpe", Icon::Video),
    ("mpeg", Icon::Video),
    ("mpeg2", Icon::Video),
    ("mpg", Icon::Video),
    ("mpv", Icon::Video),
    ("mql.yaml", Icon::Mondoo),
    ("mql.yml", Icon::Mondoo),
    ("ms", Icon::Maxscript),
    ("msg", Icon::Outlook),
    ("mson", Icon::Mson),
    ("mst", Icon::Mustache),
    ("msv", Icon::Audio),
    ("mustache", Icon::Mustache),
    ("n", Icon::Binary),
    ("ndll", Icon::Binary),
    ("ndst.json", Icon::Ndst),
    ("ndst.yaml", Icon::Ndst),
    ("ndst.yml", Icon::Ndst),
    ("ne", Icon::Nearly),
    ("nim", Icon::Nim),
    ("nimble", Icon::Nimble),
    ("nix", Icon::Nix),
    ("njsproj", Icon::Njsproj),
    ("noc", Icon::Noc),
    ("npy", Icon::Numpy),
    ("npz", Icon::Numpy),
    ("nsi", Icon::Nsi),
    ("nsv", Icon::Video),
    ("nunjucks", Icon::Nunjucks),
    ("nupkg", Icon::Nuget),
    ("nuspec", Icon::Nuget),
    ("nut", Icon::Squirrel),
    ("o", Icon::Binary),
    ("o3", Icon::Ogone),
    ("obj", Icon::Binary),
    ("ocrec", Icon::Lync),
    ("ods", Icon::Excel),
    ("oft", Icon::Outlook),
    ("oga", Icon::Audio),
    ("ogg", Icon::Audio),
    ("ogv", Icon::Video),
    ("one", Icon::Onenote),
    ("onepkg", Icon::Onenote),
    ("onetoc", Icon::Onenote),
    ("onetoc2", Icon::Onenote),
    ("opencl", Icon::Opencl),
    ("opus", Icon::Audio),
    ("org", Icon::Org),
    ("otf", Icon::Font),
    ("otm", Icon::Outlook),
    ("ovpn", Icon::Ovpn),
    ("p12", Icon::Cert),
    ("p7b", Icon::Cert),
    ("p7r", Icon::Cert),
    ("pa", Icon::Powerpoint),
    ("pas", Icon::Delphi),
    ("patch", Icon::Patch),
    ("pcd", Icon::Pcl),
    ("pck", Icon::PlsqlPackage),
    ("pcss", Icon::Postcss),
    ("pdb", Icon::Binary),
    ("pddl", Icon::Pddl),
    ("pde", Icon::Arduino),
    ("pdf", Icon::Pdf),
    ("pem", Icon::Key),
    ("pfa", Icon::Font),
    ("pfb", Icon::Font),
    ("pfx", Icon::Cert),
    ("pgsql", Icon::Pgsql),
    ("php", Icon::Php),
    ("pine", Icon::Pine),
    ("pipeline", Icon::Pipeline),
    ("pkb", Icon::PlsqlPackageBody),
    ("pkg", Icon::Package),
    ("pkh", Icon::PlsqlPackageHeader),
    ("pks", Icon::PlsqlPackageSpec),
    ("pl", Icon::Perl),
    ("pl6", Icon::Perl6),
    ("plan", Icon::PddlPlan),
    ("plantuml", Icon::Plantuml),
    ("png", Icon::Image),
    ("po", Icon::Poedit),
    ("polymer", Icon::Polymer),
    ("pony", Icon::Pony),
    ("postman_collection.json", Icon::Postman),
    ("postman_environment.json", Icon::Postman),
    ("postman_globals.json", Icon::Postman),
    ("pot", Icon::Powerpoint),
    ("potm", Icon::Powerpoint),
    ("potx", Icon::Powerpoint),
    ("pp", Icon::Puppet),
    ("ppa", Icon::Powerpoint),
    ("ppam", Icon::Powerpoint),
    ("pps", Icon::Powerpoint),
    ("ppsm", Icon::Powerpoint),
    ("ppsx", Icon::Powerpoint),
    ("ppt", Icon::Powerpoint),
    ("pptm", Icon::Powerpoint),
    ("pptx", Icon::Powerpoint),
    ("pq", Icon::Mlang),
    ("prg", Icon::Harbour),
    ("prisma", Icon::Prisma),
    ("pro", Icon::Prolog),
    ("properties", Icon::Config),
    ("proto", Icon::Protobuf),
    ("prw", Icon::Advpl),
    ("ps1", Icon::Powershell),
    ("psd", Icon::Photoshop),
    ("psd1", Icon::PowershellPsd),
    ("psm1", Icon::PowershellPsm),
    ("psmdcp", Icon::Nuget),
    ("pst", Icon::Outlook),
    ("pu", Icon::Plantuml),
    ("pub", Icon::Publisher),
    ("pug", Icon::Pug),
    ("puml", Icon::Plantuml),
    ("purs", Icon::Purescript),
    ("puz", Icon::Publisher),
    ("py", Icon::Python),
    ("pyc", Icon::Binary),
    ("pyd", Icon::Binary),
    ("pyo", Icon::Binary),
    ("pyowo", Icon::Pythowo),
    ("pyx", Icon::Cython),
    ("q", Icon::Q),
    ("qbs", Icon::Qbs),
    ("ql", Icon::Codeql),
    ("qml", Icon::Qml),
    ("qs", Icon::Qsharp),
    ("qt", Icon::Video),
    ("qvs", Icon::Qlikview),
    ("r", Icon::R),
    ("ra", Icon::Audio),
    ("rake", Icon::Rake),
    ("raml", Icon::Raml),
    ("rar", Icon::Zip),
    ("raw", Icon::Audio),
    ("rb", Icon::Ruby),
    ("re", Icon::Reason),
    ("red", Icon::Red),
    ("reg", Icon::Registry),
    ("rego", Icon::Rego),
    ("requirements.txt", Icon::Pip),
    ("res", Icon::Rescript),
    ("rex", Icon::Rexx),
    ("rkt", Icon::Racket),
    ("rm", Icon::Video),
    ("rmd", Icon::Rmd),
    ("rmvb", Icon::Video),
    ("robot", Icon::Robotframework),
    ("ron", Icon::Ron),
    ("rproj", Icon::Rproj),
    ("rq", Icon::Sparql),
    ("rs", Icon::Rust),
    ("rst", Icon::Rest),
    ("rt", Icon::Reacttemplate),
    ("rules", Icon::Prometheus),
    ("san", Icon::San),
    ("sas", Icon::Sas),
    ("sass", Icon::Sass),
    ("sbt", Icon::Sbt),
    ("scad", Icon::Openscad),
    ("scala", Icon::Scala),
    ("sce", Icon::Scilab),
    ("schema.json", Icon::JsonSchema),
    ("scpt", Icon::Binary),
    ("scptd", Icon::Binary),
    ("scss", Icon::Scss),
    ("sdl", Icon::Sdlang),
    ("sfd", Icon::Font),
    ("sh", Icon::Shell),
    ("shader", Icon::Shaderlab),
    ("sig", Icon::Onenote),
    ("sketch", Icon::Sketch),
    ("slang", Icon::Slang),
    ("sldm", Icon::Powerpoint),
    ("sldx", Icon::Powerpoint),
    ("slim", Icon::Slim),
    ("sln", Icon::Sln),
    ("sls", Icon::Saltstack),
    ("sn", Icon::Sino),
    ("snort", Icon::Snort),
    ("snupkg", Icon::Nuget),
    ("so", Icon::Binary),
    ("sol", Icon::Solidity),
    ("spe", Icon::Spacengine),
    ("sqf", Icon::Sqf),
    ("sql", Icon::Sql),
    ("sqlite", Icon::Sqlite),
    ("sqlite3", Icon::Sqlite),
    ("src", Icon::Cert),
    ("ss", Icon::Silverstripe),
    ("sss", Icon::Sss),
    ("sst", Icon::Cert),
    ("st.css", Icon::Stylable),
    ("stan", Icon::Stan),
    ("stencil", Icon::Stencil),
    ("stl", Icon::Cert),
    ("storyboard", Icon::Storyboard),
    ("sty", Icon::Tex),
    ("styl", Icon::Stylus),
    ("styled", Icon::Styled),
    ("sublime-project", Icon::Sublime),
    ("sv", Icon::Systemverilog),
    ("svelte", Icon::Svelte),
    ("svg", Icon::Svg),
    ("svi", Icon::Video),
    ("swagger", Icon::Swagger),
    ("swc", Icon::Flash),
    ("swf", Icon::Flash),
    ("swift", Icon::Swift),
    ("swig", Icon::Swig),
    ("sy", Icon::Siyuan),
    ("tag", Icon::Riot),
    ("tar", Icon::Zip),
    ("tcl", Icon::Tcl),
    ("teal", Icon::Teal),
    ("tera", Icon::Tera),
    ("tex", Icon::Tex),
    ("textile", Icon::Textile),
    ("tf", Icon::Terraform),
    ("tgz", Icon::Zip),
    ("things", Icon::OpenHab),
    ("tiff", Icon::Image),
    ("tlg", Icon::Log),
    ("todo", Icon::Todo),
    ("toit", Icon::Toit),
    ("toml", Icon::Toml),
    ("tpl", Icon::Smarty),
    ("tree", Icon::Tree),
    ("tres", Icon::Tres),
    ("ts", Icon::Typescript),
    ("ts.snap", Icon::JestSnapshot),
    ("tsbuildinfo", Icon::Tsbuildinfo),
    ("tscn", Icon::Tscn),
    ("tst", Icon::Test),
    ("tsx", Icon::Reactts),
    ("tsx.snap", Icon::JestSnapshot),
    ("tt", Icon::T4Tt),
    ("tt3", Icon::Tt),
    ("tta", Icon::Audio),
    ("ttcn3", Icon::Ttcn),
    ("ttf", Icon::Font),
    ("tuc", Icon::Tuc),
    ("twig", Icon::Twig),
    ("txt", Icon::Text),
    ("types.ps1xml", Icon::PowershellTypes),
    ("typoscript", Icon::Typo3),
    ("u", Icon::Unison),
    ("ua", Icon::Uiua),
    ("v", Icon::Verilog),
    ("vala", Icon::Vala),
    ("vapi", Icon::Vapi),
    ("vash", Icon::Vash),
    ("vb", Icon::Vb),
    ("vbhtml", Icon::Vbhtml),
    ("vbproj", Icon::Vbproj),
    ("vcxproj", Icon::Vcxproj),
    ("vhdl", Icon::Vhdl),
    ("vim", Icon::Vim),
    ("vm", Icon::Velocity),
    ("vob", Icon::Video),
    ("volt", Icon::Volt),
    ("vox", Icon::Audio),
    ("vsix", Icon::Vsix),
    ("vsixmanifest", Icon::Vsixmanifest),
    ("vue", Icon::Vue),
    ("w", Icon::Progress),
    ("wai", Icon::Wit),
    ("wasm", Icon::Wasm),
    ("wav", Icon::Audio),
    ("webm", Icon::Video),
    ("webp", Icon::Image),
    ("wgsl", Icon::Wgsl),
    ("wl", Icon::Wolfram),
    ("wll", Icon::Word),
    ("wma", Icon::Audio),
    ("wmv", Icon::Video),
    ("woff", Icon::Font),
    ("woff2", Icon::Font),
    ("wsf", Icon::Script),
    ("wt", Icon::Wikitext),
    ("wxml", Icon::Wxml),
    ("wxss", Icon::Wxss),
    ("wy", Icon::Wenyan),
    ("xcodeproj", Icon::Xcode),
    ("xfl", Icon::Xfl),
    ("xib", Icon::Xib),
    ("xlf", Icon::Xliff),
    ("xliff", Icon::Xliff),
    ("xls", Icon::Excel),
    ("xlsb", Icon::Excel),
    ("xlsm", Icon::Excel),
    ("xlsx", Icon::Excel),
    ("xmake.lua", Icon::Xmake),
    ("xml", Icon::Xml),
    ("xquery", Icon::Xquery),
    ("xsf", Icon::Infopath),
    ("xsl", Icon::Xsl),
    ("xsn", Icon::Infopath),
    ("xtp2", Icon::Infopath),
    ("xz", Icon::Zip),
    ("yaml", Icon::Yaml),
    ("yang", Icon::Yang),
    ("yml", Icon::Yaml),
    ("zig", Icon::Zig),
    ("zip", Icon::Zip),
    ("zipx", Icon::Zip),
];

pub const FILENAME_ICONS: [(&str, Icon); 825] = [
    (".all-contributorsrc", Icon::Allcontributors),
    (".angular-cli.json", Icon::Angular),
    (".angular.json", Icon::Angular),
    (".appsemblerc.yaml", Icon::Appsemble),
    (".appveyor.yml", Icon::Appveyor),
    (".babelignore", Icon::Babel),
    (".babelrc", Icon::Babel),
    (".bazelignore", Icon::BazelIgnore),
    (".bazelversion", Icon::BazelVersion),
    (".bithoundrc", Icon::Bithound),
    (".boringignore", Icon::Darcs),
    (".bowerrc", Icon::Bower),
    (".browserslistrc", Icon::Browserslist),
    (".buckconfig", Icon::Buckbuild),
    (".bzrignore", Icon::Bazaar),
    (".codacy.yaml", Icon::Codacy),
    (".codacy.yml", Icon::Codacy),
    (".codeclimate.yml", Icon::Codeclimate),
    (".codecov.yml", Icon::Codecov),
    (".coffeelintignore", Icon::Coffeelint),
    (".commitlintrc", Icon::Commitlint),
    (".condarc", Icon::Conda),
    (".config.codekit", Icon::Codekit),
    (".config.codekit2", Icon::Codekit),
    (".config.codekit3", Icon::Codekit),
    (".coveralls.yml", Icon::Coveralls),
    (".cspell.cjs", Icon::Cspell),
    (".cspell.js", Icon::Cspell),
    (".cspell.json", Icon::Cspell),
    (".cspell.yaml", Icon::Cspell),
    (".cspell.yml", Icon::Cspell),
    (".csscomb.json", Icon::Csscomb),
    (".csslintrc", Icon::Csslint),
    (".cvsignore", Icon::Cvs),
    (".cz.json", Icon::Commitizen),
    (".czrc", Icon::Commitizen),
    (".denoifyrc", Icon::Denoify),
    (".devcontainer.json", Icon::Devcontainer),
    (".doczrc", Icon::Docz),
    (".dojorc", Icon::Dojo),
    (".drone.yml", Icon::Drone),
    (".drone.yml.sig", Icon::Drone),
    (".editorconfig", Icon::Editorconfig),
    (".ember-cli", Icon::Ember),
    (".eslintcache", Icon::Eslint),
    (".eslintignore", Icon::Eslint),
    (".eslintrc", Icon::Eslint),
    (".fantasticonrc", Icon::Fantasticon),
    (".fantasticonrc.js", Icon::Fantasticon),
    (".fantasticonrc.json", Icon::Fantasticon),
    (".firebaserc", Icon::Firebase),
    (".flooignore", Icon::Floobits),
    (".flowconfig", Icon::Flow),
    (".flutter-plugins", Icon::Flutter),
    (".fossaignore", Icon::Fossa),
    (".gcloudignore", Icon::Gcloud),
    (".gitlab-ci.yml", Icon::Gitlab),
    (".gitpod.yaml", Icon::Gitpod),
    (".gitpod.yml", Icon::Gitpod),
    (".glitterrc", Icon::Glitter),
    (".graphqlconfig", Icon::GraphqlConfig),
    (".hgignore", Icon::Mercurial),
    (".htmlhintrc", Icon::Htmlhint),
    (".huskyrc", Icon::Husky),
    (".integrity.json", Icon::NsriIntegrity),
    (".jestrc", Icon::Jest),
    (".jestrc.js", Icon::Jest),
    (".jestrc.json", Icon::Jest),
    (".jpmignore", Icon::Jpm),
    (".jsbeautify", Icon::Jsbeautify),
    (".jsbeautifyrc", Icon::Jsbeautify),
    (".jscpd.json", Icon::Jscpd),
    (".jshintignore", Icon::Jshint),
    (".jshintrc", Icon::Jshint),
    (".kitchen.yml", Icon::Kitchenci),
    (".kiteignore", Icon::Kite),
    (".licrc", Icon::Licensebat),
    (".lighthouserc.cjs", Icon::Lighthouse),
    (".lighthouserc.js", Icon::Lighthouse),
    (".lighthouserc.json", Icon::Lighthouse),
    (".lighthouserc.yaml", Icon::Lighthouse),
    (".lighthouserc.yml", Icon::Lighthouse),
    (".lintstagedrc", Icon::Lintstagedrc),
    (".lintstagedrc.cjs", Icon::Lintstagedrc),
    (".lintstagedrc.js", Icon::Lintstagedrc),
    (".lintstagedrc.json", Icon::Lintstagedrc),
    (".lintstagedrc.mjs", Icon::Lintstagedrc),
    (".lintstagedrc.yaml", Icon::Lintstagedrc),
    (".lintstagedrc.yml", Icon::Lintstagedrc),
    (".markdownlintignore", Icon::MarkdownlintIgnore),
    (".markdownlintrc", Icon::Markdownlint),
    (".metadata", Icon::Flutter),
    (".mtn-ignore", Icon::Monotone),
    (".nest-cli.json", Icon::Nestjs),
    (".nestconfig.json", Icon::Nestjs),
    (".node-version", Icon::Node),
    (".nowignore", Icon::Vercel),
    (".npmignore", Icon::Npm),
    (".npmrc", Icon::Npm),
    (".nsriignore", Icon::Nsri),
    (".nsrirc", Icon::Nsri),
    (".nuxtignore", Icon::Nuxt),
    (".nuxtrc", Icon::Nuxt),
    (".nvmrc", Icon::Node),
    (".nycrc", Icon::Nyc),
    (".nycrc.json", Icon::Nyc),
    (".objidconfig", Icon::Objidconfig),
    (".p4ignore", Icon::Helix),
    (".packages", Icon::FlutterPackage),
    (".php_cs", Icon::Phpcsfixer),
    (".php_cs.dist", Icon::Phpcsfixer),
    (".phraseapp.yml", Icon::Phraseapp),
    (".postcssrc", Icon::Postcssconfig),
    (".postcssrc.cjs", Icon::Postcssconfig),
    (".postcssrc.js", Icon::Postcssconfig),
    (".postcssrc.json", Icon::Postcssconfig),
    (".postcssrc.ts", Icon::Postcssconfig),
    (".postcssrc.yaml", Icon::Postcssconfig),
    (".postcssrc.yml", Icon::Postcssconfig),
    (".pre-commit-config.yaml", Icon::Precommit),
    (".prettierignore", Icon::Prettier),
    (".prettierrc", Icon::Prettier),
    (".prettierrc.cjs", Icon::Prettier),
    (".prettierrc.js", Icon::Prettier),
    (".prettierrc.json", Icon::Prettier),
    (".prettierrc.json5", Icon::Prettier),
    (".prettierrc.mjs", Icon::Prettier),
    (".prettierrc.toml", Icon::Prettier),
    (".prettierrc.yaml", Icon::Prettier),
    (".prettierrc.yml", Icon::Prettier),
    (".pyup", Icon::Pyup),
    (".pyup.yml", Icon::Pyup),
    (".rehypeignore", Icon::Rehype),
    (".rehyperc", Icon::Rehype),
    (".remarkignore", Icon::Remark),
    (".remarkrc", Icon::Remark),
    (".renovaterc", Icon::Renovate),
    (".renovaterc.json", Icon::Renovate),
    (".replit", Icon::Replit),
    (".retextignore", Icon::Retext),
    (".retextrc", Icon::Retext),
    (".rspec", Icon::Rspec),
    (".rubocop.yml", Icon::Rubocop),
    (".rubocop_todo.yml", Icon::Rubocop),
    (".ruby-version", Icon::Ruby),
    (".sailsrc", Icon::Sails),
    (".sapphirerc", Icon::SapphireFrameworkCli),
    (".sapphirerc.json", Icon::SapphireFrameworkCli),
    (".sapphirerc.yml", Icon::SapphireFrameworkCli),
    (".sentryclirc", Icon::Sentry),
    (".sequelizerc", Icon::Sequelize),
    (".shellcheckrc", Icon::Shellcheck),
    (".snyk", Icon::Snyk),
    (".solidarity", Icon::Solidarity),
    (".solidarity.json", Icon::Solidarity),
    (".stryker.conf.cjs", Icon::Stryker),
    (".stryker.conf.conf", Icon::Stryker),
    (".stryker.conf.js", Icon::Stryker),
    (".stryker.conf.json", Icon::Stryker),
    (".stryker.conf.mjs", Icon::Stryker),
    (".stryker.config.cjs", Icon::Stryker),
    (".stryker.config.conf", Icon::Stryker),
    (".stryker.config.js", Icon::Stryker),
    (".stryker.config.json", Icon::Stryker),
    (".stryker.config.mjs", Icon::Stryker),
    (".stylelintcache", Icon::Stylelint),
    (".stylelintignore", Icon::Stylelint),
    (".stylelintrc", Icon::Stylelint),
    (".stylish-haskell.yaml", Icon::StylishHaskell),
    (".svnignore", Icon::Subversion),
    (".swcrc", Icon::Swc),
    (".taurignore", Icon::Tauri),
    (".testcaferc.json", Icon::Testcafe),
    (".tfignore", Icon::Tfs),
    (".tool-versions", Icon::Config),
    (".travis.yml", Icon::Travis),
    (".unibeautifyrc", Icon::Unibeautify),
    (".vercelignore", Icon::Vercel),
    (".vscode-test.js", Icon::VscodeTest),
    (".vscode-test.json", Icon::VscodeTest),
    (".vscode-test.mjs", Icon::VscodeTest),
    (".vscodeignore", Icon::Vscode),
    (".vuerc", Icon::Vueconfig),
    (".wallaby.coffee", Icon::Wallaby),
    (".wallaby.conf.coffee", Icon::Wallaby),
    (".wallaby.conf.js", Icon::Wallaby),
    (".wallaby.conf.json", Icon::Wallaby),
    (".wallaby.conf.ts", Icon::Wallaby),
    (".wallaby.js", Icon::Wallaby),
    (".wallaby.json", Icon::Wallaby),
    (".wallaby.ts", Icon::Wallaby),
    (".watchmanconfig", Icon::Watchmanconfig),
    (".yamllint", Icon::Yamllint),
    (".yarn-integrity", Icon::Yarn),
    (".yarn-metadata.json", Icon::Yarn),
    (".yarnclean", Icon::Yarn),
    (".yarnignore", Icon::Yarn),
    (".yarnrc", Icon::Yarn),
    (".yarnrc.yml", Icon::Yarn),
    (".yaspeller.json", Icon::Yandex),
    (".yaspellerrc", Icon::Yandex),
    (".yo-rc.json", Icon::Yeoman),
    ("Pulumi.dev.yaml", Icon::Pulumi),
    ("Pulumi.dev.yml", Icon::Pulumi),
    ("Pulumi.prod.yaml", Icon::Pulumi),
    ("Pulumi.prod.yml", Icon::Pulumi),
    ("Pulumi.yaml", Icon::Pulumi),
    ("Pulumi.yml", Icon::Pulumi),
    ("Shuttle.toml", Icon::Shuttle),
    ("angular-cli.json", Icon::Angular),
    ("angular.json", Icon::Angular),
    ("api-extractor-base.json", Icon::ApiExtractor),
    ("api-extractor.json", Icon::ApiExtractor),
    ("app-definition.yaml", Icon::Appsemble),
    ("app.config.js", Icon::Expo),
    ("app.config.json", Icon::Expo),
    ("app.config.json5", Icon::Expo),
    ("app.json", Icon::Expo),
    ("appveyor.yml", Icon::Appveyor),
    ("astro.config.cjs", Icon::Astroconfig),
    ("astro.config.js", Icon::Astroconfig),
    ("astro.config.mjs", Icon::Astroconfig),
    ("astro.config.ts", Icon::Astroconfig),
    ("aurelia.json", Icon::Aurelia),
    ("berksfile", Icon::Chef),
    ("berksfile.lock", Icon::Chef),
    ("biome.json", Icon::Biome),
    ("bitbucket-pipelines.yml", Icon::Bitbucketpipeline),
    ("bower.json", Icon::Bower),
    ("browserslist", Icon::Browserslist),
    ("build.ninja", Icon::Ninja),
    ("bunfig.toml", Icon::Bunfig),
    ("capacitor.config.json", Icon::Capacitor),
    ("cargo.lock", Icon::Cargo),
    ("cargo.toml", Icon::Cargo),
    ("checkstyle.json", Icon::Haxecheckstyle),
    ("chefignore", Icon::Chef),
    ("circle.yml", Icon::Circleci),
    ("codecov.yml", Icon::Codecov),
    ("codeowners", Icon::Codeowners),
    ("coffeelint.json", Icon::Coffeelint),
    ("commitlint.config.cjs", Icon::Commitlint),
    ("commitlint.config.js", Icon::Commitlint),
    ("commitlint.config.ts", Icon::Commitlint),
    ("composer.json", Icon::Composer),
    ("composer.lock", Icon::Composer),
    ("conanfile.py", Icon::Conan),
    ("conanfile.txt", Icon::Conan),
    ("config.codekit", Icon::Codekit),
    ("config.codekit2", Icon::Codekit),
    ("config.codekit3", Icon::Codekit),
    ("copying", Icon::License),
    ("copying.lesser", Icon::License),
    ("crowdin.yml", Icon::Crowdin),
    ("cspell.cjs", Icon::Cspell),
    ("cspell.config.cjs", Icon::Cspell),
    ("cspell.config.js", Icon::Cspell),
    ("cspell.config.json", Icon::Cspell),
    ("cspell.config.yaml", Icon::Cspell),
    ("cspell.config.yml", Icon::Cspell),
    ("cspell.js", Icon::Cspell),
    ("cspell.json", Icon::Cspell),
    ("cspell.yaml", Icon::Cspell),
    ("cspell.yml", Icon::Cspell),
    ("cypress.config.cjs", Icon::Cypress),
    ("cypress.config.js", Icon::Cypress),
    ("cypress.config.mjs", Icon::Cypress),
    ("cypress.config.ts", Icon::Cypress),
    ("cypress.env.json", Icon::Cypress),
    ("cypress.json", Icon::Cypress),
    ("deno.json", Icon::Deno),
    ("deno.jsonc", Icon::Deno),
    ("deno.lock", Icon::Deno),
    ("dependabot.yaml", Icon::Dependabot),
    ("dependabot.yml", Icon::Dependabot),
    ("dependencies.yml", Icon::Dependencies),
    ("devcontainer.json", Icon::Devcontainer),
    ("docker-compose.test.yml", Icon::Dockertest),
    ("doppler-template.yaml", Icon::Doppler),
    ("doppler.yaml", Icon::Doppler),
    ("e2e-spec.mts", Icon::Testts),
    ("e2e-spec.ts", Icon::Testts),
    ("e2e-spec.tsx", Icon::Testts),
    ("e2e-test.mts", Icon::Testts),
    ("e2e-test.ts", Icon::Testts),
    ("e2e-test.tsx", Icon::Testts),
    ("ecosystem.config.cjs", Icon::Pm2),
    ("ecosystem.config.js", Icon::Pm2),
    ("ecosystem.config.json", Icon::Pm2),
    ("ecosystem.config.yaml", Icon::Pm2),
    ("ecosystem.config.yml", Icon::Pm2),
    ("esbuild.cjs", Icon::Esbuild),
    ("esbuild.config.cjs", Icon::Esbuild),
    ("esbuild.config.js", Icon::Esbuild),
    ("esbuild.config.mjs", Icon::Esbuild),
    ("esbuild.config.ts", Icon::Esbuild),
    ("esbuild.js", Icon::Esbuild),
    ("esbuild.mjs", Icon::Esbuild),
    ("esbuild.ts", Icon::Esbuild),
    ("eslint.config.js", Icon::Eslint),
    ("fantasticonrc", Icon::Fantasticon),
    ("fantasticonrc.js", Icon::Fantasticon),
    ("fantasticonrc.json", Icon::Fantasticon),
    ("favicon.ico", Icon::Favicon),
    ("firebase.json", Icon::Firebasehosting),
    ("firestore.indexes.json", Icon::Firestore),
    ("firestore.rules", Icon::Firestore),
    ("flareact.config.js", Icon::Flareact),
    ("formkit.config.cjs", Icon::Formkit),
    ("formkit.config.js", Icon::Formkit),
    ("formkit.config.mjs", Icon::Formkit),
    ("formkit.config.ts", Icon::Formkit),
    ("funding.yml", Icon::Funding),
    ("fuse.js", Icon::Fusebox),
    ("gatsby-browser.js", Icon::Gatsby),
    ("gatsby-browser.ts", Icon::Gatsby),
    ("gatsby-browser.tsx", Icon::Gatsby),
    ("gatsby-config.js", Icon::Gatsby),
    ("gatsby-config.mjs", Icon::Gatsby),
    ("gatsby-config.ts", Icon::Gatsby),
    ("gatsby-node.js", Icon::Gatsby),
    ("gatsby-node.mjs", Icon::Gatsby),
    ("gatsby-node.ts", Icon::Gatsby),
    ("gatsby-ssr.js", Icon::Gatsby),
    ("gatsby-ssr.ts", Icon::Gatsby),
    ("gatsby-ssr.tsx", Icon::Gatsby),
    ("gemfile", Icon::Bundler),
    ("gemfile.lock", Icon::Bundler),
    ("gitpod.yaml", Icon::Gitpod),
    ("gitpod.yml", Icon::Gitpod),
    ("glide.yml", Icon::Glide),
    ("go.mod", Icon::GoPackage),
    ("go.sum", Icon::GoPackage),
    ("go.work", Icon::GoWork),
    ("go.work.sum", Icon::GoWork),
    ("greenkeeper.json", Icon::Greenkeeper),
    ("gridsome.client.js", Icon::Gridsome),
    ("gridsome.client.ts", Icon::Gridsome),
    ("gridsome.config.js", Icon::Gridsome),
    ("gridsome.config.ts", Icon::Gridsome),
    ("gridsome.server.js", Icon::Gridsome),
    ("gridsome.server.ts", Icon::Gridsome),
    ("gruntfile.babel.cjs", Icon::Grunt),
    ("gruntfile.babel.coffee", Icon::Grunt),
    ("gruntfile.babel.js", Icon::Grunt),
    ("gruntfile.babel.ts", Icon::Grunt),
    ("gruntfile.cjs", Icon::Grunt),
    ("gruntfile.coffee", Icon::Grunt),
    ("gruntfile.js", Icon::Grunt),
    ("gruntfile.ts", Icon::Grunt),
    ("gulpfile.babel.coffee", Icon::Gulp),
    ("gulpfile.babel.js", Icon::Gulp),
    ("gulpfile.babel.mjs", Icon::Gulp),
    ("gulpfile.babel.ts", Icon::Gulp),
    ("gulpfile.coffee", Icon::Gulp),
    ("gulpfile.esm.coffee", Icon::Gulp),
    ("gulpfile.esm.js", Icon::Gulp),
    ("gulpfile.esm.mjs", Icon::Gulp),
    ("gulpfile.esm.ts", Icon::Gulp),
    ("gulpfile.js", Icon::Gulp),
    ("gulpfile.mjs", Icon::Gulp),
    ("gulpfile.ts", Icon::Gulp),
    ("hardhat.config.js", Icon::Hardhat),
    ("hardhat.config.ts", Icon::Hardhat),
    ("horusec-config.json", Icon::Horusec),
    ("husky.config.js", Icon::Husky),
    ("ignore-glob", Icon::Fossil),
    ("include.xml", Icon::Lime),
    ("ionic.config.json", Icon::Ionic),
    ("ionic.project", Icon::Ionic),
    ("jakefile", Icon::Jake),
    ("jakefile.js", Icon::Jake),
    ("jasmine.json", Icon::Jasmine),
    ("jest.config.babel.js", Icon::Jest),
    ("jest.json", Icon::Jest),
    ("jsbeautify", Icon::Jsbeautify),
    ("jsbeautifyrc", Icon::Jsbeautify),
    ("jsconfig.json", Icon::Jsconfig),
    ("karma.conf.coffee", Icon::Karma),
    ("karma.conf.js", Icon::Karma),
    ("karma.conf.ts", Icon::Karma),
    ("kitchen.yml", Icon::Kitchenci),
    ("layout.htm", Icon::Layout),
    ("layout.html", Icon::Layout),
    ("lerna.json", Icon::Lerna),
    ("licence", Icon::License),
    ("license", Icon::License),
    ("license-apache", Icon::License),
    ("license-mit", Icon::License),
    ("lint-staged.config.cjs", Icon::Lintstagedrc),
    ("lint-staged.config.js", Icon::Lintstagedrc),
    ("lint-staged.config.mjs", Icon::Lintstagedrc),
    ("mailing.config.json", Icon::Mailing),
    ("manifest", Icon::Manifest),
    ("manifest.bak", Icon::ManifestBak),
    ("manifest.skip", Icon::ManifestSkip),
    ("master.css.js", Icon::MasterCo),
    ("master.css.json", Icon::MasterCo),
    ("master.css.mjs", Icon::MasterCo),
    ("master.css.ts", Icon::MasterCo),
    ("master.js", Icon::MasterCo),
    ("master.json", Icon::MasterCo),
    ("master.mjs", Icon::MasterCo),
    ("master.ts", Icon::MasterCo),
    ("maven.config", Icon::Maven),
    ("mocha.opts", Icon::Mocha),
    ("modernizr", Icon::Modernizr),
    ("moleculer.config.js", Icon::Moleculer),
    ("moleculer.config.json", Icon::Moleculer),
    ("moleculer.config.ts", Icon::Moleculer),
    ("motif.json", Icon::Motif),
    ("nest-cli.json", Icon::Nestjs),
    ("nestconfig.json", Icon::Nestjs),
    ("netlify.toml", Icon::Netlify),
    ("next.config.cjs", Icon::Next),
    ("next.config.js", Icon::Next),
    ("next.config.mjs", Icon::Next),
    ("ng-tailwind.js", Icon::NgTailwind),
    ("nginx.conf", Icon::Nginx),
    ("nodemon.json", Icon::Nodemon),
    ("now.json", Icon::Vercel),
    ("npm-shrinkwrap.json", Icon::Npm),
    ("nsri.config.js", Icon::Nsri),
    ("nx.json", Icon::Nx),
    ("package-lock.json", Icon::Npm),
    ("package.json", Icon::Npm),
    ("paket.dependencies", Icon::Paket),
    ("paket.local", Icon::Paket),
    ("paket.lock", Icon::Paket),
    ("paket.references", Icon::Paket),
    ("paket.template", Icon::Paket),
    ("peeky.config.js", Icon::Peeky),
    ("peeky.config.mjs", Icon::Peeky),
    ("peeky.config.ts", Icon::Peeky),
    ("phpstan.dist.neon", Icon::Phpstan),
    ("phpstan.neon", Icon::Phpstan),
    ("phpunit", Icon::Phpunit),
    ("phpunit.xml", Icon::Phpunit),
    ("phpunit.xml.dist", Icon::Phpunit),
    ("playwright.config.js", Icon::Playwright),
    ("playwright.config.ts", Icon::Playwright),
    ("pnpm-lock.yaml", Icon::Pnpm),
    ("pnpm-workspace.yaml", Icon::Pnpm),
    ("pnpmfile.js", Icon::Pnpm),
    ("poetry.lock", Icon::Poetry),
    ("policyfile.lock.json", Icon::Chef),
    ("policyfile.rb", Icon::Chef),
    ("postcss.config.cjs", Icon::Postcssconfig),
    ("postcss.config.js", Icon::Postcssconfig),
    ("postcss.config.ts", Icon::Postcssconfig),
    ("preact.config.js", Icon::Preact),
    ("prettier.config.cjs", Icon::Prettier),
    ("prettier.config.coffee", Icon::Prettier),
    ("prettier.config.js", Icon::Prettier),
    ("prettier.config.mjs", Icon::Prettier),
    ("prettier.config.ts", Icon::Prettier),
    ("procfile", Icon::Procfile),
    ("protractor.conf.coffee", Icon::Protractor),
    ("protractor.conf.js", Icon::Protractor),
    ("protractor.conf.ts", Icon::Protractor),
    ("publiccode.yml", Icon::Publiccode),
    ("pubspec.lock", Icon::FlutterPackage),
    ("pubspec.yaml", Icon::FlutterPackage),
    ("py.typed", Icon::Pytyped),
    ("qmldir", Icon::Qmldir),
    ("quasar.conf.js", Icon::Quasar),
    ("quasar.config.js", Icon::Quasar),
    ("rakefile", Icon::Rake),
    ("razzle.config.js", Icon::Razzle),
    ("replit.nix", Icon::Replit),
    ("robots.txt", Icon::Robots),
    ("rollup.config.cjs", Icon::Rollup),
    ("rollup.config.coffee", Icon::Rollup),
    ("rollup.config.common.cjs", Icon::Rollup),
    ("rollup.config.common.coffee", Icon::Rollup),
    ("rollup.config.common.js", Icon::Rollup),
    ("rollup.config.common.mjs", Icon::Rollup),
    ("rollup.config.common.ts", Icon::Rollup),
    ("rollup.config.dev.cjs", Icon::Rollup),
    ("rollup.config.dev.coffee", Icon::Rollup),
    ("rollup.config.dev.js", Icon::Rollup),
    ("rollup.config.dev.mjs", Icon::Rollup),
    ("rollup.config.dev.ts", Icon::Rollup),
    ("rollup.config.js", Icon::Rollup),
    ("rollup.config.mjs", Icon::Rollup),
    ("rollup.config.prod.cjs", Icon::Rollup),
    ("rollup.config.prod.coffee", Icon::Rollup),
    ("rollup.config.prod.js", Icon::Rollup),
    ("rollup.config.prod.mjs", Icon::Rollup),
    ("rollup.config.prod.ts", Icon::Rollup),
    ("rollup.config.ts", Icon::Rollup),
    ("rome.json", Icon::Rome),
    ("rust-toolchain", Icon::RustToolchain),
    ("rust-toolchain.toml", Icon::RustToolchain),
    ("serverless.js", Icon::Serverless),
    ("serverless.json", Icon::Serverless),
    ("serverless.ts", Icon::Serverless),
    ("serverless.yml", Icon::Serverless),
    ("slash-up.config.js", Icon::Slashup),
    ("snapcraft.yaml", Icon::Snapcraft),
    ("snaplet.config.js", Icon::Snaplet),
    ("snaplet.config.ts", Icon::Snaplet),
    ("spec.js", Icon::Testjs),
    ("spec.jsx", Icon::Testjs),
    ("spec.mjs", Icon::Testjs),
    ("spec.mts", Icon::Testts),
    ("spec.ts", Icon::Testts),
    ("spec.tsx", Icon::Testts),
    ("spin.toml", Icon::Spin),
    ("store.config.json", Icon::EasMetadata),
    ("stories.js", Icon::Storybook),
    ("stories.jsx", Icon::Storybook),
    ("stories.mdx", Icon::Storybook),
    ("stories.ts", Icon::Storybook),
    ("stories.tsx", Icon::Storybook),
    ("story.js", Icon::Storybook),
    ("story.jsx", Icon::Storybook),
    ("story.mdx", Icon::Storybook),
    ("story.ts", Icon::Storybook),
    ("story.tsx", Icon::Storybook),
    ("stryker-config.cjs", Icon::Stryker),
    ("stryker-config.conf", Icon::Stryker),
    ("stryker-config.js", Icon::Stryker),
    ("stryker-config.json", Icon::Stryker),
    ("stryker-config.mjs", Icon::Stryker),
    ("stryker.conf.cjs", Icon::Stryker),
    ("stryker.conf.conf", Icon::Stryker),
    ("stryker.conf.js", Icon::Stryker),
    ("stryker.conf.json", Icon::Stryker),
    ("stryker.conf.mjs", Icon::Stryker),
    ("stryker.config.cjs", Icon::Stryker),
    ("stryker.config.conf", Icon::Stryker),
    ("stryker.config.js", Icon::Stryker),
    ("stryker.config.json", Icon::Stryker),
    ("stryker.config.mjs", Icon::Stryker),
    ("stryker4s.cjs", Icon::Stryker),
    ("stryker4s.conf", Icon::Stryker),
    ("stryker4s.js", Icon::Stryker),
    ("stryker4s.json", Icon::Stryker),
    ("stryker4s.mjs", Icon::Stryker),
    ("svelte.config.js", Icon::Svelteconfig),
    ("symfony.lock", Icon::Symfony),
    ("tamagui.cjs", Icon::Tamagui),
    ("tamagui.config.cjs", Icon::Tamagui),
    ("tamagui.config.cts", Icon::Tamagui),
    ("tamagui.config.js", Icon::Tamagui),
    ("tamagui.config.mjs", Icon::Tamagui),
    ("tamagui.config.mts", Icon::Tamagui),
    ("tamagui.config.ts", Icon::Tamagui),
    ("tamagui.cts", Icon::Tamagui),
    ("tamagui.js", Icon::Tamagui),
    ("tamagui.mjs", Icon::Tamagui),
    ("tamagui.mts", Icon::Tamagui),
    ("tamagui.ts", Icon::Tamagui),
    ("tauri.conf.json", Icon::Tauri),
    ("test.js", Icon::Testjs),
    ("test.jsx", Icon::Testjs),
    ("test.mjs", Icon::Testjs),
    ("test.mts", Icon::Testts),
    ("test.ts", Icon::Testts),
    ("test.tsx", Icon::Testts),
    ("tox.ini", Icon::Tox),
    ("truffle-config.js", Icon::Truffle),
    ("truffle-config.ts", Icon::Truffle),
    ("trunk.yaml", Icon::Trunk),
    ("tsconfig.app.json", Icon::Tsconfig),
    ("tsconfig.base.json", Icon::Tsconfig),
    ("tsconfig.build.json", Icon::Tsconfig),
    ("tsconfig.cjs.json", Icon::Tsconfig),
    ("tsconfig.common.json", Icon::Tsconfig),
    ("tsconfig.dev.json", Icon::Tsconfig),
    ("tsconfig.development.json", Icon::Tsconfig),
    ("tsconfig.e2e.json", Icon::Tsconfig),
    ("tsconfig.eslint.json", Icon::Tsconfig),
    ("tsconfig.esm.json", Icon::Tsconfig),
    ("tsconfig.json", Icon::Tsconfig),
    ("tsconfig.lib.json", Icon::Tsconfig),
    ("tsconfig.lib.prod.json", Icon::Tsconfig),
    ("tsconfig.mjs.json", Icon::Tsconfig),
    ("tsconfig.node.json", Icon::Tsconfig),
    ("tsconfig.prod.json", Icon::Tsconfig),
    ("tsconfig.production.json", Icon::Tsconfig),
    ("tsconfig.server.json", Icon::Tsconfig),
    ("tsconfig.spec.json", Icon::Tsconfig),
    ("tsconfig.staging.json", Icon::Tsconfig),
    ("tsconfig.test.json", Icon::Tsconfig),
    ("tsconfig.types.json", Icon::Tsconfig),
    ("tslint.json", Icon::Tslint),
    ("tslint.yaml", Icon::Tslint),
    ("tslint.yml", Icon::Tslint),
    ("turbo.json", Icon::Turbo),
    ("typedoc.js", Icon::Typedoc),
    ("typedoc.json", Icon::Typedoc),
    ("unibeautify.config.js", Icon::Unibeautify),
    ("unlicence", Icon::Unlicense),
    ("unlicense", Icon::Unlicense),
    ("uno.config.js", Icon::Unocss),
    ("uno.config.mjs", Icon::Unocss),
    ("uno.config.mts", Icon::Unocss),
    ("uno.config.ts", Icon::Unocss),
    ("unocss.config.js", Icon::Unocss),
    ("unocss.config.mjs", Icon::Unocss),
    ("unocss.config.mts", Icon::Unocss),
    ("unocss.config.ts", Icon::Unocss),
    ("vagrantfile", Icon::Vagrant),
    ("vapor.yml", Icon::Vapor),
    ("vercel.json", Icon::Vercel),
    ("vite.config.cjs", Icon::Vite),
    ("vite.config.cts", Icon::Vite),
    ("vite.config.js", Icon::Vite),
    ("vite.config.mjs", Icon::Vite),
    ("vite.config.mts", Icon::Vite),
    ("vite.config.ts", Icon::Vite),
    ("vitest.config.cjs", Icon::Vitest),
    ("vitest.config.cts", Icon::Vitest),
    ("vitest.config.js", Icon::Vitest),
    ("vitest.config.mjs", Icon::Vitest),
    ("vitest.config.mts", Icon::Vitest),
    ("vitest.config.ts", Icon::Vitest),
    ("vitest.projects.cjs", Icon::Vitest),
    ("vitest.projects.cts", Icon::Vitest),
    ("vitest.projects.js", Icon::Vitest),
    ("vitest.projects.json", Icon::Vitest),
    ("vitest.projects.mjs", Icon::Vitest),
    ("vitest.projects.mts", Icon::Vitest),
    ("vitest.projects.ts", Icon::Vitest),
    ("vitest.workspace.cjs", Icon::Vitest),
    ("vitest.workspace.cts", Icon::Vitest),
    ("vitest.workspace.js", Icon::Vitest),
    ("vitest.workspace.json", Icon::Vitest),
    ("vitest.workspace.mjs", Icon::Vitest),
    ("vitest.workspace.mts", Icon::Vitest),
    ("vitest.workspace.ts", Icon::Vitest),
    ("vue.config.cjs", Icon::Vueconfig),
    ("vue.config.js", Icon::Vueconfig),
    ("vue.config.mjs", Icon::Vueconfig),
    ("wallaby.coffee", Icon::Wallaby),
    ("wallaby.conf.coffee", Icon::Wallaby),
    ("wallaby.conf.js", Icon::Wallaby),
    ("wallaby.conf.json", Icon::Wallaby),
    ("wallaby.conf.ts", Icon::Wallaby),
    ("wallaby.js", Icon::Wallaby),
    ("wallaby.json", Icon::Wallaby),
    ("wallaby.ts", Icon::Wallaby),
    ("wally.lock", Icon::Wally),
    ("wally.toml", Icon::Wally),
    ("wdio.cjs", Icon::Wdio),
    ("wdio.conf.cjs", Icon::Wdio),
    ("wdio.conf.cts", Icon::Wdio),
    ("wdio.conf.js", Icon::Wdio),
    ("wdio.conf.json", Icon::Wdio),
    ("wdio.conf.mjs", Icon::Wdio),
    ("wdio.conf.mts", Icon::Wdio),
    ("wdio.conf.ts", Icon::Wdio),
    ("wdio.cts", Icon::Wdio),
    ("wdio.js", Icon::Wdio),
    ("wdio.json", Icon::Wdio),
    ("wdio.mjs", Icon::Wdio),
    ("wdio.mts", Icon::Wdio),
    ("wdio.ts", Icon::Wdio),
    ("webpack.base.conf.cjs", Icon::Webpack),
    ("webpack.base.conf.coffee", Icon::Webpack),
    ("webpack.base.conf.js", Icon::Webpack),
    ("webpack.base.conf.mjs", Icon::Webpack),
    ("webpack.base.conf.ts", Icon::Webpack),
    ("webpack.common.cjs", Icon::Webpack),
    ("webpack.common.coffee", Icon::Webpack),
    ("webpack.common.js", Icon::Webpack),
    ("webpack.common.mjs", Icon::Webpack),
    ("webpack.common.ts", Icon::Webpack),
    ("webpack.config.babel.cjs", Icon::Webpack),
    ("webpack.config.babel.coffee", Icon::Webpack),
    ("webpack.config.babel.js", Icon::Webpack),
    ("webpack.config.babel.mjs", Icon::Webpack),
    ("webpack.config.babel.ts", Icon::Webpack),
    ("webpack.config.base.babel.cjs", Icon::Webpack),
    ("webpack.config.base.babel.coffee", Icon::Webpack),
    ("webpack.config.base.babel.js", Icon::Webpack),
    ("webpack.config.base.babel.mjs", Icon::Webpack),
    ("webpack.config.base.babel.ts", Icon::Webpack),
    ("webpack.config.base.cjs", Icon::Webpack),
    ("webpack.config.base.coffee", Icon::Webpack),
    ("webpack.config.base.js", Icon::Webpack),
    ("webpack.config.base.mjs", Icon::Webpack),
    ("webpack.config.base.ts", Icon::Webpack),
    ("webpack.config.build.cjs", Icon::Webpack),
    ("webpack.config.build.coffee", Icon::Webpack),
    ("webpack.config.build.js", Icon::Webpack),
    ("webpack.config.build.mjs", Icon::Webpack),
    ("webpack.config.build.ts", Icon::Webpack),
    ("webpack.config.cjs", Icon::Webpack),
    ("webpack.config.coffee", Icon::Webpack),
    ("webpack.config.common.babel.cjs", Icon::Webpack),
    ("webpack.config.common.babel.coffee", Icon::Webpack),
    ("webpack.config.common.babel.js", Icon::Webpack),
    ("webpack.config.common.babel.mjs", Icon::Webpack),
    ("webpack.config.common.babel.ts", Icon::Webpack),
    ("webpack.config.common.cjs", Icon::Webpack),
    ("webpack.config.common.coffee", Icon::Webpack),
    ("webpack.config.common.js", Icon::Webpack),
    ("webpack.config.common.mjs", Icon::Webpack),
    ("webpack.config.common.ts", Icon::Webpack),
    ("webpack.config.dev.babel.cjs", Icon::Webpack),
    ("webpack.config.dev.babel.coffee", Icon::Webpack),
    ("webpack.config.dev.babel.js", Icon::Webpack),
    ("webpack.config.dev.babel.mjs", Icon::Webpack),
    ("webpack.config.dev.babel.ts", Icon::Webpack),
    ("webpack.config.dev.cjs", Icon::Webpack),
    ("webpack.config.dev.coffee", Icon::Webpack),
    ("webpack.config.dev.js", Icon::Webpack),
    ("webpack.config.dev.mjs", Icon::Webpack),
    ("webpack.config.dev.ts", Icon::Webpack),
    ("webpack.config.development.babel.cjs", Icon::Webpack),
    ("webpack.config.development.babel.coffee", Icon::Webpack),
    ("webpack.config.development.babel.js", Icon::Webpack),
    ("webpack.config.development.babel.mjs", Icon::Webpack),
    ("webpack.config.development.babel.ts", Icon::Webpack),
    ("webpack.config.development.cjs", Icon::Webpack),
    ("webpack.config.development.coffee", Icon::Webpack),
    ("webpack.config.development.js", Icon::Webpack),
    ("webpack.config.development.mjs", Icon::Webpack),
    ("webpack.config.development.ts", Icon::Webpack),
    ("webpack.config.js", Icon::Webpack),
    ("webpack.config.mjs", Icon::Webpack),
    ("webpack.config.prod.babel.cjs", Icon::Webpack),
    ("webpack.config.prod.babel.coffee", Icon::Webpack),
    ("webpack.config.prod.babel.js", Icon::Webpack),
    ("webpack.config.prod.babel.mjs", Icon::Webpack),
    ("webpack.config.prod.babel.ts", Icon::Webpack),
    ("webpack.config.prod.cjs", Icon::Webpack),
    ("webpack.config.prod.coffee", Icon::Webpack),
    ("webpack.config.prod.js", Icon::Webpack),
    ("webpack.config.prod.mjs", Icon::Webpack),
    ("webpack.config.prod.ts", Icon::Webpack),
    ("webpack.config.production.babel.cjs", Icon::Webpack),
    ("webpack.config.production.babel.coffee", Icon::Webpack),
    ("webpack.config.production.babel.js", Icon::Webpack),
    ("webpack.config.production.babel.mjs", Icon::Webpack),
    ("webpack.config.production.babel.ts", Icon::Webpack),
    ("webpack.config.production.cjs", Icon::Webpack),
    ("webpack.config.production.coffee", Icon::Webpack),
    ("webpack.config.production.js", Icon::Webpack),
    ("webpack.config.production.mjs", Icon::Webpack),
    ("webpack.config.production.ts", Icon::Webpack),
    ("webpack.config.staging.babel.cjs", Icon::Webpack),
    ("webpack.config.staging.babel.coffee", Icon::Webpack),
    ("webpack.config.staging.babel.js", Icon::Webpack),
    ("webpack.config.staging.babel.mjs", Icon::Webpack),
    ("webpack.config.staging.babel.ts", Icon::Webpack),
    ("webpack.config.staging.cjs", Icon::Webpack),
    ("webpack.config.staging.coffee", Icon::Webpack),
    ("webpack.config.staging.js", Icon::Webpack),
    ("webpack.config.staging.mjs", Icon::Webpack),
    ("webpack.config.staging.ts", Icon::Webpack),
    ("webpack.config.test.babel.cjs", Icon::Webpack),
    ("webpack.config.test.babel.coffee", Icon::Webpack),
    ("webpack.config.test.babel.js", Icon::Webpack),
    ("webpack.config.test.babel.mjs", Icon::Webpack),
    ("webpack.config.test.babel.ts", Icon::Webpack),
    ("webpack.config.test.cjs", Icon::Webpack),
    ("webpack.config.test.coffee", Icon::Webpack),
    ("webpack.config.test.js", Icon::Webpack),
    ("webpack.config.test.mjs", Icon::Webpack),
    ("webpack.config.test.ts", Icon::Webpack),
    ("webpack.config.ts", Icon::Webpack),
    ("webpack.dev.cjs", Icon::Webpack),
    ("webpack.dev.coffee", Icon::Webpack),
    ("webpack.dev.conf.cjs", Icon::Webpack),
    ("webpack.dev.conf.coffee", Icon::Webpack),
    ("webpack.dev.conf.js", Icon::Webpack),
    ("webpack.dev.conf.mjs", Icon::Webpack),
    ("webpack.dev.conf.ts", Icon::Webpack),
    ("webpack.dev.js", Icon::Webpack),
    ("webpack.dev.mjs", Icon::Webpack),
    ("webpack.dev.ts", Icon::Webpack),
    ("webpack.local.cjs", Icon::Webpack),
    ("webpack.local.coffee", Icon::Webpack),
    ("webpack.local.js", Icon::Webpack),
    ("webpack.local.mjs", Icon::Webpack),
    ("webpack.local.ts", Icon::Webpack),
    ("webpack.main.config.cjs", Icon::Webpack),
    ("webpack.main.config.coffee", Icon::Webpack),
    ("webpack.main.config.js", Icon::Webpack),
    ("webpack.main.config.mjs", Icon::Webpack),
    ("webpack.main.config.ts", Icon::Webpack),
    ("webpack.mix.cjs", Icon::Webpack),
    ("webpack.mix.coffee", Icon::Webpack),
    ("webpack.mix.js", Icon::Webpack),
    ("webpack.mix.mjs", Icon::Webpack),
    ("webpack.mix.ts", Icon::Webpack),
    ("webpack.plugins.cjs", Icon::Webpack),
    ("webpack.plugins.coffee", Icon::Webpack),
    ("webpack.plugins.js", Icon::Webpack),
    ("webpack.plugins.mjs", Icon::Webpack),
    ("webpack.plugins.ts", Icon::Webpack),
    ("webpack.prod.cjs", Icon::Webpack),
    ("webpack.prod.coffee", Icon::Webpack),
    ("webpack.prod.conf.cjs", Icon::Webpack),
    ("webpack.prod.conf.coffee", Icon::Webpack),
    ("webpack.prod.conf.js", Icon::Webpack),
    ("webpack.prod.conf.mjs", Icon::Webpack),
    ("webpack.prod.conf.ts", Icon::Webpack),
    ("webpack.prod.js", Icon::Webpack),
    ("webpack.prod.mjs", Icon::Webpack),
    ("webpack.prod.ts", Icon::Webpack),
    ("webpack.renderer.config.cjs", Icon::Webpack),
    ("webpack.renderer.config.coffee", Icon::Webpack),
    ("webpack.renderer.config.js", Icon::Webpack),
    ("webpack.renderer.config.mjs", Icon::Webpack),
    ("webpack.renderer.config.ts", Icon::Webpack),
    ("webpack.rules.cjs", Icon::Webpack),
    ("webpack.rules.coffee", Icon::Webpack),
    ("webpack.rules.js", Icon::Webpack),
    ("webpack.rules.mjs", Icon::Webpack),
    ("webpack.rules.ts", Icon::Webpack),
    ("webpack.test.conf.cjs", Icon::Webpack),
    ("webpack.test.conf.coffee", Icon::Webpack),
    ("webpack.test.conf.js", Icon::Webpack),
    ("webpack.test.conf.mjs", Icon::Webpack),
    ("webpack.test.conf.ts", Icon::Webpack),
    ("wercker.yml", Icon::Wercker),
    ("windi.config.js", Icon::Windi),
    ("windi.config.ts", Icon::Windi),
    ("wpml-config.xml", Icon::Wpml),
    ("yarn.lock", Icon::Yarn),
];
