name: CI
on: [push, pull_request]
jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'web-client/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install -g license-checker
      - name: Check JavaScript Licenses
        working-directory: web-client
        run:  license-checker --summary --onlyAllow="MIT;Apache-2.0;BSD-2-Clause" --excludePackages="spa-client@0.0.0"
      - name: Check Rust Licenses
        uses: EmbarkStudios/cargo-deny-action@v1
