name: RS checks (v1)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/rs-checks-v1.yml"
      - "**/*.rs"
      - "**/*.proto"
      - "**/Cargo.toml"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, stable]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev protobuf-compiler
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --manifest-path crates/v1/Cargo.toml
        env:
          RUSTFLAGS: ${{matrix.rustflags}} ${{env.RUSTFLAGS}}

  msrv:
    name: Rust MSRV
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: install native dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev protobuf-compiler
      - id: msrv
        name: Find out the MSRV from Cargo.toml
        run: |
          msrv=$(yq -e '.package.rust-version' ./crates/v1/crates/devtools/Cargo.toml);
          echo "msrv=$msrv" >> "$GITHUB_OUTPUT"
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.msrv.outputs.msrv }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --manifest-path crates/v1/Cargo.toml --tests

  clippy:
    name: Clippy
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: install native dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --manifest-path crates/v1/Cargo.toml -- -Dclippy::all -Dclippy::pedantic

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install rustfmt with nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --manifest-path crates/v1/Cargo.toml -- --check
      - run: cargo fmt --manifest-path examples/tauri-v1/Cargo.toml -- --check

  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Check Cargo Deny (crates/v1)
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          manifest-path: crates/v1/Cargo.toml
      - name: Check Cargo Deny (examples/tauri-v1)
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          manifest-path: examples/tauri-v1/Cargo.toml
