name: RS checks (v2)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/rs-checks-v2.yml"
      - "**/*.rs"
      - "**/*.proto"
      - "**/Cargo.toml"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, stable]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: install native dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 protobuf-compiler
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace
        env:
          RUSTFLAGS: ${{matrix.rustflags}} ${{env.RUSTFLAGS}}

  msrv:
    name: Rust MSRV
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: install native dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 protobuf-compiler
      - id: msrv
        name: Find out the MSRV from Cargo.toml
        run: |
          msrv=$(yq -e '.workspace.package.rust-version' ./Cargo.toml);
          echo "msrv=$msrv" >> "$GITHUB_OUTPUT"
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.msrv.outputs.msrv }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --workspace --tests

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: install native dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace -- -Dclippy::all -Dclippy::pedantic

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install rustfmt with nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Check Rust Code
        uses: EmbarkStudios/cargo-deny-action@v2
