name: Web Client Tests

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "web-client/**"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "web-client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "web-client/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: web-client
        run: pnpm install install

      - name: Format
        working-directory: web-client
        run: pnpm prettier --check '**/*.{ts,tsx,js,jsx,json}'

      - name: Linting
        working-directory: web-client
        run: pnpm lint

      - name: Unit tests
        working-directory: web-client
        run: pnpm test -- --run
